### ISSUE TITLE
bot_facing variable seems to be either always true or always false. Needs a fix

### ISSUE THREAD

**Issue by Sam-Si** [WAZAAAAA0/TekkenBot#6]
`bot_facing` = self.GetValueFromDataBlock(player_data_frame, self.c['GameDataAddress']['facing'])

This used to work in previous versions. But now it seems to be broken. Which makes `IsBotOnLeft` either true or false for the rest of the game. Ideally, it should change when player one is changing its side.

**Comment by WAZAAAAA0** [comment]
supposedly fixed with the new patch addresses

**Comment by Sam-Si** [comment]
Thanks @WAZAAAAA0 I will test it and let you know :)

**Comment by Sam-Si** [comment]
@WAZAAAAA0 The issue is not fixed yet. I have tried doing multiple things but as of now, I can't find a way to tell whether the bot is on the left side or right side.

Could you please re-open this issue?
Thanks

**Comment by Sam-Si** [comment]
@WAZAAAAA0 I checked in the code and there is no issue with the code. Then I loaded CE_TekkenBot and OPPONENT_SIDE seems to be always 1 I think that's the real problem.

I am not good with CE sadly. Could someone correct OPPONENT_SIDE address or give out any hints on how to do it?

Thanks

**Comment by Sam-Si** [comment]
[TekkenGame-Win64-Shipping.zip](https://github.com/WAZAAAAA0/TekkenBot/files/2654832/TekkenGame-Win64-Shipping.zip)

I tried finding the correct address for OPPONENT_SIDE could you please test on your system if those addresses work for you as well. I saw some tutorials and that's the best I could do.

**Comment by Sam-Si** [comment]
@WAZAAAAA0 
I have fixed the issue from my end and created a pull request.
Please check it on your side and accept the pull request.

**Comment by Sam-Si** [comment]
@WAZAAAAA0 Please close the issue.

**Comment by cooluk** [comment]
so, was it fixed? I suffered that opponent side issue :-(
